[package]
name = "gh-discussion-export"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
thiserror = "2.0.18"

[dev-dependencies]
mockall = "0.14.0"
